sonar.projectKey=ecse429-todo-manager-challenger
sonar.projectName=ECSE 429 Todo Manager Challenger
sonar.projectVersion=1.5.5
sonar.sourceEncoding=UTF-8
sonar.sources=thingifier-1.5.5/challenger/src/main/java
sonar.java.binaries=thingifier-1.5.5/challenger/target/classes
sonar.java.source=11
